#!/usr/bin/env sh

# Include common helper functions & variables
. "$PROXYCTL_HOME/common.sh"

INFO_TXT=CACHE
WARN_TXT=CACHE
DIE_TXT=CACHE

description() {
    echo "Persists proxy environment variables across new shell sessions"
}

enable() {
    local url=""
    if [ "$PROXYCTL_PROTO" = "http" ] || [ "$PROXYCTL_PROTO" = "https" ]; then
        url="http://$PROXYCTL_HOST:$PROXYCTL_PORT"
    else
        url="$PROXYCTL_PROTO://$PROXYCTL_HOST:$PROXYCTL_PORT"
    fi

    local cache_dir
    cache_dir=$(dirname "$PROXYCTL_CACHE")

    mkdir -p "$cache_dir"
    chmod 700 "$cache_dir" 2>/dev/null || true

    # Write atomically via tempfile to avoid race conditions with newly opened shells
    local tmp="$cache_dir/.env.tmp.$$"

    {
        echo "# Auto-generated by proxyctl. Do not edit manually."
        echo "export http_proxy='$url'"
        echo "export https_proxy='$url'"
        echo "export HTTP_PROXY='$url'"
        echo "export HTTPS_PROXY='$url'"
        echo "export ftp_proxy='$url'"
        echo "export rsync_proxy='$url'"
        echo "export all_proxy='$url'"
        echo "export no_proxy='$PROXYCTL_NO_PROXY'"
        echo "export NO_PROXY='$PROXYCTL_NO_PROXY'"
    } > "$tmp"

    chmod 600 "$tmp"
    mv -f "$tmp" "$PROXYCTL_CACHE"

    info "Persistent shell environment cached at ${C_BLUE}$PROXYCTL_CACHE${C_RESET}"
}

disable() {
    if [ -f "$PROXYCTL_CACHE" ]; then
        rm -f "$PROXYCTL_CACHE"
        info "Persistent shell cache removed"
    else
        info "Persistent shell cache is already inactive"
    fi
}

status() {
    if [ -f "$PROXYCTL_CACHE" ]; then
        info "Persistent cache is ${C_GREEN}ACTIVE${C_RESET} ($PROXYCTL_CACHE)"
    else
        info "Persistent cache is ${C_RED}INACTIVE${C_RESET}"
    fi
}

# --- Module Dispatcher ---
case "$1" in
    description)
        description
        ;;
    enable|disable|status)
        [ -z "$PROXYCTL_CACHE" ] && die "PROXYCTL_CACHE is not set. The cache module requires a target file."
        "$1"
        ;;
    *)
        die "Module ${C_BLUE}'cache'${C_RESET} does not support command: $1"
        ;;
esac
