#!/usr/bin/env bash


_XPROXY_CACHE="$HOME/.xproxy_cache"

_XPROXY_PROTOS=("http" "https" "ftp" "rsync" "all")

_XPROXY_NO_PROXY="localhost,127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,*.local"

if [ -f "$_XPROXY_CACHE" ]; then
	source "$_XPROXY_CACHE"
fi

function _xproxy_set() {

	local proxy_profile="$1"

	# proxy variables inside the profile file
	local SOCKS_ENABLE  
	local SOCKS_HOST="127.0.0.1" 
	local SOCKS_PORT="10808"  
	local SOCKS_VERSION="socks5h"
	local HTTP_ENABLE 
	local HTTP_HOST="127.0.0.1"
	local HTTP_PORT="10808" 

	if [ ! -f "$proxy_profile" ]; then
		echo "$proxy_profile not found!" >& 2
		return 1;
	fi
	source "$proxy_profile"

	echo "loading profile from $proxy_profile"
	
	local proxy_url="" 
	if [ "$SOCKS_ENABLE" = "true" ]; then
		proxy_url="$SOCKS_VERSION://$SOCKS_HOST:$SOCKS_PORT"
	fi 	

	if [ "$HTTP_ENABLE" = "true" ]; then
		proxy_url="http://$HTTP_HOST:$HTTP_PORT"
	fi	

	if [ -z "$proxy_url" ]; then
		echo "socks and http are both disabled, nothing to do..."
		return 0
	fi

	# set proxy settings via environmental variables for current shell instance
	for proto in "${_XPROXY_PROTOS[@]}"; do
		export "${proto}_proxy"="$proxy_url"
		export "${proto^^}_PROXY"="$proxy_url"
	done
	export no_proxy="${_XPROXY_NO_PROXY}"
	export NO_PROXY="${_XPROXY_NO_PROxy}"

	echo "env variables set to $proxy_url"


	# set proxy settings for future shell instances
	# WARNING: other current shell instances won't follow these proxy settings
	echo "# This file is automatically created by xproxy, DO NOT EDIT!" > "$_XPROXY_CACHE"
	for proto in "${_XPROXY_PROTOS[@]}"; do
		echo "export ${proto}_proxy=\"$proxy_url\"" >> "$_XPROXY_CACHE"
		echo "export ${proto^^}_PROXY=\"$proxy_url\"" >> "$_XPROXY_CACHE"
	done
	echo "export no_proxy=\"$_XPROXY_NO_PROXY\"" >> "$_XPROXY_CACHE"
	echo "export NO_PROXY=\"$_XPROXY_NO_PROXY\"" >> "$_XPROXY_CACHE"

	echo "cache file created for future shells"


	# set proxy setting for gnome compatibles
	gsettings set org.gnome.system.proxy mode 'manual'
	# set socks setting if enabled
	if [ "$SOCKS_ENABLE" = "true" ]; then
		gsettings set org.gnome.system.proxy.socks host "$SOCKS_HOST"
		gsettings set org.gnome.system.proxy.socks port "$SOCKS_PORT"
	else 
		# clean the socks settings to prevent any intervention
		gsettings set org.gnome.system.proxy.socks host ""
		gsettings set org.gnome.system.proxy.socks port 0
	fi

	local protos=("http" "https" "ftp")
	# set other protocols to http proxy if enabled
	if [ "$HTTP_ENABLE" = "true" ]; then
		for proto in "${protos[@]}"; do
			gsettings set org.gnome.system.proxy."$proto" host "$HTTP_HOST"
			gsettings set org.gnome.system.proxy."$proto" port "$HTTP_PORT"
		done
	else
		# clean the other settings to prevent any intervention
		for proto in "${protos[@]}"; do
			gsettings set org.gnome.system.proxy."$proto" host ""
			gsettings set org.gnome.system.proxy."$proto" port 0
		done
	fi
	gsettings set org.gnome.system.proxy ignore-hosts "['$_XPROXY_NO_PROXY']"

	echo "gnome setting is set"


	# set proxy settings for kde compatibles
	kwriteconfig6 --file kioslaverc --group "Proxy Settings" --key ProxyType 1
	# set socks setting if enabled
	if [ "$SOCKS_ENABLE" = "true" ]; then
		kwriteconfig6 --file kioslaverc --group "Proxy Settings" \
			      --key socksProxy "$SOCKS_VERSION://"$SOCKS_HOST":"$SOCKS_PORT""
	else 
		kwriteconfig6 --file kioslaverc --group "Proxy Settings" --key socksProxy ""

	fi
	if [ "$HTTP_ENABLE" = "true" ]; then
		for proto in "${protos[@]}"; do
			kwriteconfig6 --file kioslaverc --group "Proxy Settings" \
				      --key "$proto"Proxy "http://"$HTTP_HOST":"$HTTP_PORT""
		done
	else
		# clean the other settings to prevent any intervention
		for proto in "${protos[@]}"; do
			kwriteconfig6 --file kioslaverc --group "Proxy Settings" --key "$proto"Proxy ""
		done
	fi

	# Set ignored hosts
        kwriteconfig6 --file kioslaverc --group "Proxy Settings" --key NoProxyFor "$_XPROXY_NO_PROXY"

	# apply changes by restarting kde's network settings
	dbus-send --type=signal /KIO/Scheduler org.kde.KIO.Scheduler.reparseSlaveConfiguration string:""

	echo "kde setting is set"

}

function _xproxy_unset() {

	# unset proxy settings via environment variables for current shell instance
	for proto in "${_XPROXY_PROTOS[@]}"; do
		unset "${proto}_proxy"
		unset "${proto^^}_PROXY"
	done
	unset no_proxy
	unset NO_PROXY


	# unset proxy settings for future shell instances
	# WARNING: other current shell instances will continue to use the previous proxy settings
	if [ -f "$_XPROXY_CACHE" ]; then
		rm -f "$_XPROXY_CACHE"
	fi

	# unset proxy setting for gnome compatibles
	gsettings set org.gnome.system.proxy mode 'none'

	# set proxy settings for kde compatibles
	kwriteconfig6 --file kioslaverc --group "Proxy Settings" --key ProxyType 0

	# apply changes by restarting kde's network settings
	dbus-send --type=signal /KIO/Scheduler org.kde.KIO.Scheduler.reparseSlaveConfiguration string:""


}

function _xproxy_status() {

	# Initialize color variables
	local RED=$(tput setaf 1)
	local RESET=$(tput sgr0)

	# check proxy environment variable settings
	for proto in ${_XPROXY_PROTOS[@]}; do
		local proto_proxy="${proto}_proxy"
		local PROTO_PROXY="${proto^^}_PROXY"

		if [ -n "${!proto_proxy}" ]; then 
			echo "${proto_proxy} = ${!proto_proxy}"
		else 
			echo "${RED}${proto_proxy} is NOT set${RESET}"
		fi

		if [ -n "${!PROTO_PROXY}" ]; then
			echo "${PROTO_PROXY} = ${!PROTO_PROXY}"
		else 
			echo "${RED}${PROTO_PROXY} is NOT set${RESET}"
		fi
	done

	# check existance of cache file for future shells 
	if [ -f "$_XPROXY_CACHE" ]; then
		echo "cache file exists"
	else 
		echo "${RED}cache file does NOT exist${RESET}"
	fi

	# check gnome proxy settings
	if [ $(gsettings get org.gnome.system.proxy mode) = "'manual'" ]; then
		echo "gnome setting is set"
	else 
		echo "${RED}gnome setting is NOT set${RESET}"
	fi


	# check kde proxy settings
	if [ $(kreadconfig6 --file kioslaverc --group "Proxy Settings" --key ProxyType) = "1" ]; then
		echo "KDE setting is set"
	else 
		echo "${RED}KDE setting is NOT set${RESET}"
	fi

}

function xproxy() {

	local cmd=${1:-status};

	case "$cmd" in
	"set")
		local profile_file=${2:-"$HOME/.xproxy_profile"}
		_xproxy_set $profile_file
	;;
	"unset")
		_xproxy_unset
	;;
	"status")
		_xproxy_status
	;;
	*)
		echo "invalid command"
	;;
	esac
}
